# -*- coding: utf-8 -*-
"""Cars.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJt1ZkoXlK11IU2jwpuTa3_QwuMdxJyP

YouTube Tutorial for this project can be found in link:
https://www.youtube.com/watch?v=fhiUl7f5DnI

Cars Analysis Project
Link: https://corgis-edu.github.io/corgis/csv/cars/
"""

import pandas as pd

url = "https://corgis-edu.github.io/corgis/datasets/csv/cars/cars.csv"
df = pd.read_csv(url)

df.head(10)

print(df.size)
print(df.shape)

df.isnull().sum()

df.columns

#df.head(2)
df['Identification.Make'].value_counts()

#df.head(2)
df[df['Identification.Make'].isin(['Lamborghini', 'Rolls-Royce'])]

# code assigning filter to df then saving as high_rollers
# class_23 = titanic[(titanic["Pclass"] == 2) | (titanic["Pclass"] == 3)]  THIS IS AN EXAMPLE PULLED FROM stackoverflow
high_rollers = df[(df['Identification.Make'] == 'Infiniti') | (df['Identification.Make'] == 'Jeep')]
high_rollers.head(100)

#running simple plot across determined x and y
import matplotlib.pyplot as plt
high_rollers.plot('Identification.Year', 'Fuel Information.City mpg')

